name: snake_2d
description: A 2D snake game made by Flutter Bonfire Engine

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flame: ^1.7.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/jsons/
    - assets/images/map/
    - assets/images/snake/
    - assets/images/fruit/